CREATE TABLE Member (
    ID SERIAL PRIMARY KEY,
    FullName VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Phone VARCHAR(20) NOT NULL,
    Height NUMERIC NOT NULL,
    Weight NUMERIC NOT NULL,
    WeightGoal NUMERIC NOT NULL
);

CREATE TABLE Trainer (
    ID SERIAL PRIMARY KEY,
    FullName VARCHAR(255) NOT NULL,
    DaysAvailable VARCHAR(255) NOT NULL,
    StartTime VARCHAR(255) NOT NULL,
    EndTime VARCHAR(255) NOT NULL
);

CREATE TABLE AdministrativeStaff (
    ID SERIAL PRIMARY KEY,
    FullName VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL
);

CREATE TABLE TrainingSession (
    ID SERIAL PRIMARY KEY,
    MemberID INTEGER REFERENCES Member(ID),
    TrainerID INTEGER REFERENCES Trainer(ID),
    SessionDay VARCHAR(255) NOT NULL,
    StartTime VARCHAR(255) NOT NULL,
    EndTime VARCHAR(255) NOT NULL
);

CREATE TABLE RoomBooking (
    ID SERIAL PRIMARY KEY,
    RoomID INTEGER,
    MemberID INTEGER REFERENCES Member(ID),
    BookingDay VARCHAR(255) NOT NULL,
    StartTime VARCHAR(255) NOT NULL,
    EndTime VARCHAR(255) NOT NULL
);

CREATE TABLE Equipment (
    ID SERIAL PRIMARY KEY,
    EquipmentName VARCHAR(255) NOT NULL,
    MaintenanceStatus VARCHAR(255) NOT NULL,
    Availability VARCHAR(255) NOT NULL
);

CREATE TABLE Class (
    ID SERIAL PRIMARY KEY,
    ClassName VARCHAR(255) NOT NULL,
    ClassDay VARCHAR(255) NOT NULL,
    StartTime VARCHAR(255) NOT NULL,
    EndTime VARCHAR(255) NOT NULL
);

CREATE TABLE Billing (
    ID SERIAL PRIMARY KEY,
    MemberID INTEGER REFERENCES Member(ID),
    Amount NUMERIC NOT NULL,
    CardNumber VARCHAR(255) NOT NULL,
    CardType VARCHAR(255) NOT NULL
);
